PKGNAMENW=--pkgname vlc-record
PKGNAMECL=--pkgname vlc-record-classic
REQUIRES=--requires "libqtcore4, libqtgui4, libqt4-network, libqt4-sql-sqlite, vlc, libvlc5, libqt4-xml"
REQUIRESCLC=--requires "libqtcore4, libqtgui4, libqt4-network, libqt4-sql-sqlite, vlc, libqt4-xml"
MAINT=--maintainer "Jo2003 \(coujo@gmx.net\)"
PKGVERCL=--pkgversion ${CLMAJORVER}.${MINORVER}
PKGVERNW=--pkgversion ${NWMAJORVER}.${MINORVER}
PKGGRP=--pkggroup video
PKGSRC=--pkgsource "https://code.google.com/p/vlc-record"
